package tripitics

import "strings"

// Source identifies the system that produced an .ics. The iCalendar container
// is standard (RFC 5545), but how a booking is encoded in the free-text fields
// — flight idents, check-in markers, type tags — is producer-specific, so the
// right Mapper is chosen per source. New sources (Kayak, Google, …) slot in as
// additional Mappers without touching the parser.
type Source string

const (
	SourceUnknown Source = ""
	SourceTripIt  Source = "tripit"
)

// Detect returns the producer of a parsed calendar, or SourceUnknown. TripIt's
// exports are generated by "Bennu", so PRODID doesn't identify them — the
// @tripit.com event UIDs and the "TripIt" marker in the calendar name/desc do.
func Detect(cal *Calendar) Source {
	if strings.Contains(cal.Name, "TripIt") || strings.Contains(cal.Desc, "tripit.com") {
		return SourceTripIt
	}
	for _, e := range cal.Events {
		if strings.Contains(e.UID, "@tripit.com") {
			return SourceTripIt
		}
	}
	return SourceUnknown
}

// Mapper turns a parsed calendar from a recognised source into Aerly shapes.
type Mapper interface {
	MapTrip(cal *Calendar) *MappedTrip
}

// tripItMapper is the Mapper for TripIt exports.
type tripItMapper struct{}

// MapTrip implements Mapper, mapping a TripIt calendar (see mapTripIt).
func (tripItMapper) MapTrip(cal *Calendar) *MappedTrip { return mapTripIt(cal) }

// MapperFor returns the Mapper for a source, or (nil, false) when there is no
// source-specific mapper — the caller should then fall back (e.g. to the LLM
// extractor for an unrecognised calendar).
func MapperFor(src Source) (Mapper, bool) {
	switch src {
	case SourceTripIt:
		return tripItMapper{}, true
	default:
		return nil, false
	}
}

// Map detects a calendar's source and maps it, returning the mapped trip, the
// detected source, and whether a source-specific mapper handled it. ok is false
// for an unrecognised calendar (mt is nil); the caller falls back.
func Map(cal *Calendar) (mt *MappedTrip, src Source, ok bool) {
	src = Detect(cal)
	m, ok := MapperFor(src)
	if !ok {
		return nil, src, false
	}
	return m.MapTrip(cal), src, true
}
