package importics

import "strings"

// Source identifies the system that produced an .ics. The iCalendar container
// is standard (RFC 5545), but how a booking is encoded in the free-text fields
// — flight idents, check-in markers, type tags — is producer-specific, so the
// right Mapper is chosen per source. New sources (Kayak, Google, …) slot in as
// additional Mappers without touching the parser.
type Source string

const (
	SourceUnknown Source = ""
	SourceTripIt  Source = "tripit"
	SourceKayak   Source = "kayak"
)

// Detect returns the producer of a parsed calendar, or SourceUnknown. TripIt's
// exports are generated by "Bennu", so PRODID doesn't identify them — the
// @tripit.com event UIDs and the "TripIt" marker in the calendar name/desc do.
// Kayak, by contrast, stamps its own PRODID and @kayak.com event UIDs.
func Detect(cal *Calendar) Source {
	if strings.Contains(cal.Name, "TripIt") || strings.Contains(cal.Desc, "tripit.com") {
		return SourceTripIt
	}
	if strings.Contains(cal.ProdID, "Kayak") || strings.Contains(strings.ToUpper(cal.Name), "KAYAK") {
		return SourceKayak
	}
	for _, e := range cal.Events {
		switch {
		case strings.Contains(e.UID, "@tripit.com"):
			return SourceTripIt
		case strings.Contains(e.UID, "@kayak.com"):
			return SourceKayak
		}
	}
	return SourceUnknown
}

// Mapper turns a parsed calendar from a recognised source into Aerly shapes. A
// single .ics may describe one trip (TripIt's per-trip export) or several
// (Kayak's account feed), so a Mapper returns a slice.
type Mapper interface {
	MapTrips(cal *Calendar) []*MappedTrip
}

// tripItMapper is the Mapper for TripIt exports (one trip per file).
type tripItMapper struct{}

// MapTrips implements Mapper, mapping a TripIt calendar (see mapTripIt).
func (tripItMapper) MapTrips(cal *Calendar) []*MappedTrip {
	if mt := mapTripIt(cal); mt != nil {
		return []*MappedTrip{mt}
	}
	return nil
}

// kayakMapper is the Mapper for Kayak's account feed (many trips per file).
type kayakMapper struct{}

// MapTrips implements Mapper, splitting a Kayak calendar into its trips (see
// mapKayak).
func (kayakMapper) MapTrips(cal *Calendar) []*MappedTrip { return mapKayak(cal) }

// MapperFor returns the Mapper for a source, or (nil, false) when there is no
// source-specific mapper — the caller should then fall back (e.g. to the LLM
// extractor for an unrecognised calendar).
func MapperFor(src Source) (Mapper, bool) {
	switch src {
	case SourceTripIt:
		return tripItMapper{}, true
	case SourceKayak:
		return kayakMapper{}, true
	default:
		return nil, false
	}
}

// MapAll detects a calendar's source and maps every trip it contains, returning
// the mapped trips, the detected source, and whether a source-specific mapper
// handled it. ok is false for an unrecognised calendar (trips is nil); the
// caller falls back. Use this for bulk import, where one Kayak .ics expands into
// several trips.
func MapAll(cal *Calendar) (trips []*MappedTrip, src Source, ok bool) {
	src = Detect(cal)
	m, ok := MapperFor(src)
	if !ok {
		return nil, src, false
	}
	return m.MapTrips(cal), src, true
}

// Map detects a calendar's source and maps it, returning the first trip — a
// back-compat convenience for single-trip callers (the propose path). ok is
// false for an unrecognised or empty calendar (mt is nil). Prefer MapAll for
// import, which preserves every trip in a multi-trip feed.
func Map(cal *Calendar) (mt *MappedTrip, src Source, ok bool) {
	trips, src, ok := MapAll(cal)
	if !ok || len(trips) == 0 {
		return nil, src, false
	}
	return trips[0], src, true
}
